### ISSUE TITLE
Error Cost

### ISSUE THREAD

**Issue by dhanipro** [slaveofcode/rajaongkir#2]
hi, saya memiliki error pada bagian ini
cost = api.cost_between_city(55, 23, 1000, 'all')

saya menggunakan python 3.7

pesan errror adalah

raise ApiErrorException('Response Api is None, cannot fetch the status of api')
rajaongkir.api.ApiErrorException: Response Api is None, cannot fetch the status of api

Untuk api yang lainnya bekerja dengan baik seperti
# get province list
list_of_city = api.provinces()

# get cities based on province_id 
list_of_city = api.cities_by_province(9)

Mohon bantuannya

**Comment by Rahmat-Afriyadi** [comment]
sama cuy gw nyoba juga gk bisa

**Comment by i-Programer** [comment]
Sama
