### ISSUE TITLE
Get "all" courier doesn't work

### ISSUE THREAD

**Issue by hhidayat** [slaveofcode/rajaongkir#4]
Halo there, I have used your package (thank's for making it, it's really helpful), however when I trying get "all" courier it raised an error "raise ApiErrorException('Response Api is None, cannot fetch the status of api".
Please give me an advice. Thanks.

**Comment by slaveofcode** [comment]
Hi @hhidayat it seems "all" courier was dropped if we take the API reference at https://rajaongkir.com/dokumentasi/starter#cost-request. 

But if you had the request api is working for "all" courier, then I'll be happy to see some PR about it.
